name: RoshamboGame Auto Test on Push
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Show current path
        run: pwd
      - name: Run Maven Lifecycle up to package
        run: cd RoshamboGame && mvn --batch-mode --update-snapshots package